### ISSUE TITLE
Consistency between "directionality"

### ISSUE THREAD

**Issue by tmelliott** [iNZightVIT/iNZightPlots#106]
One-way barcode uses x-axes (by default), while boxplot, violin etc use y-axis. Personally I think it'd be nicer (esp. when flipping through different graphs) for the direction to be the same. Other one-way numeric is x-axis, left-to-right (dot plot, histogram), so maybe this should be taken across to violin/box?

Likely extends to other plot types too (anything with two variables should have them on the same axis, etc).

**Comment by daniel-barnett** [comment]
I'm in two minds about this. I agree with you about the consistency and would prefer it all the same way, however to do that, the outputted R would need an extra `coord_flip()` because the default is vertical for those ones (violin, etc). 

I think probably the best option is to rotate them though - it's not like we're adding some hacky, complicated code.

**Comment by tmelliott** [comment]
Adding the flip is simple enough, and you could always include a little comment after it:
```r
ggplot(...) + ... +
    coord_flip() # consistent axes across various plot types within iNZight
```

**Comment by daniel-barnett** [comment]
I've also just realised that this makes some of the backend code a bit simpler too so I think it's best all around.
