### ISSUE TITLE
Optional visibility of trend lines

### ISSUE THREAD

**Issue by tmelliott** [iNZightVIT/iNZightPlots#35]
Additional option to add all trend lines, but only display those the user has chosen when converted to HTML.

```{r}
iNZightPlot(x, y, data = d, all.trend = TRUE)
if (all.trend) {
  visible.trends = list(linear = "linear" %in% opts$trend,
                                 quadratic = "quadratic" %in% opts$trend, ... etc)
  trend = c("linear", "quadtratic", "cubic")
  #.. do plot ..#
  attr(obj, "visible.trends") = visible.trend
 
 ... return (obj)
}
```

Something like that, anyway ...

**Comment by tmelliott** [comment]
OK I honestly think this would be easier to mess with in the dialog/call ... i.e., check what trends are checked to create some "visible trends" variable, temporarily set trends to all, generate SVG, attach svg saying "only show these ones", then reset the trends ... or something like that.

**Comment by ysoh286** [comment]
@tmelliott Is it possible to add all the trend lines/confidence intervals onto the plot before exporting if they want this information?  (similar to how we have checkboxes for selecting trend and CI information)

The plot in iNZight will have all the trend lines present, but on the interactive version, there would be toggles to show these trends and some useful (if any) information about them.

```
#user could pick call for exporting all trends
pl <- iNZightPlot(wt, mpg, data = mtcars, trend = c("linear", "quadratic", "cubic", ..))
#then we export:
exportHTML(pl)
```
The same could apply to inference information like confidence intervals on dot plots and bar plots.

```
# user picks call for inference before exporting, which returns both mean and median 
# values in object pl
pl <- iNZightPlot(wt, data = mtcars, inference.type = "conf")
```
... but in a case of which a user wants both comparison and confidence, that might not be possible since they can only choose one. 

It does mean that not every plot exported will have this - it would only apply for when the user has specifically asked for it.

**Comment by tmelliott** [comment]
@ysoh286 
Ok - my idea was, instead of going through and adding these things "invisibly" to EVERY plot, instead messing with the export function so ...

```
# 1: see what's visible
pl <- iNZightPlot(..., trend = c("linear", "cubic"))

# 2: save that, somehow ...
visible <- list(trends = pl$trend-stuff, ...)

# 3: modify the plot call to do everything
pl <- iNZightPlot(..., trend = c("linear", "quadratic", "cubic"))

# 4: export that, including a list of the visibility settings
exportHTML(pl, visibility.options = visible)
```

Equiv for conf/comp intervals, and any other information. I'm not exactly sure where the best place to implement this would be (perhaps `exportHTML.function()` could do it, but probably not due to the way iNZight passes in variables).

**Comment by tmelliott** [comment]
Closing because I doubt it'll happen at this point.
